### ISSUE TITLE
Error resolving "adafruit-requests" when installing

### ISSUE THREAD

**Issue by hugodahl** [adafruit/Adafruit_CircuitPython_OAuth2#2]
When installing locally, using the command `pip install -v adafruit-circuitpython-oauth` (in a Python3 venv), the following error occurs:

```text
ERROR: Cannot install adafruit-circuitpython-oauth2==1.0.0 and adafruit-circuitpython-oauth2==1.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    adafruit-circuitpython-oauth2 1.0.1 depends on adafruit-requests
    adafruit-circuitpython-oauth2 1.0.0 depends on adafruit-requests

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

I'm not familiar with pip, pypi and the package system, but taking a look around, I noticed that in the [setup.py file - Line 39](https://github.com/adafruit/Adafruit_CircuitPython_OAuth2/blob/f69d454f5a2f2298f18e20c0f539076e379aca0d/setup.py#L39), there's a requirement for `adafruit-requests`. That package doesn't exist on pypi, but I suspect that perhaps the required package name might be `adafruit-circuitpython-requests`.

**Comment by brentru** [comment]
Fixed in #3, released in https://github.com/adafruit/Adafruit_CircuitPython_OAuth2/releases/tag/1.0.2
